site_name: Recipes

nav:
    - welcome: index.md
    - egg fried rice: egg_fried_rice.md
    - tartar: tartar.md
    - goose sous-vide: sous_vide_goose.md
theme:
    name: null
    custom_dir: 'theme/'

extra_css:
    - css/style.css