site_name: Recipes

nav:
    - Welcome: index.md
    - Egg Fried Rice: egg_fried_rice.md
    - Tartare: tartare.md
    - Goose Sous-vide: sous_vide_goose.md
theme:
    name: null
    custom_dir: 'theme/'

extra_css:
    - css/style.css