site_name: Recipes

nav:
    - Welcome: 0_welcome.md # 0 so that its at the top of the folder
    - Bone Marrow: bone_marrow.md
    - Ceviche: ceviche.md
    - Chili: chili.md
    - Egg Fried Rice: egg_fried_rice.md
    - Goose Sous-vide: sous_vide_goose.md 
    - Tartare: tartare.md
theme:
    name: null
    custom_dir: 'theme/'

extra_css:
    - css/style.css