site_name: Recipes

nav:
    - Welcome: index.md # 0 so that its at the top of the folder
    - Bone Marrow: bone_marrow.md
    - Ceviche: ceviche.md
    - Chili: chili.md
    - Egg Fried Rice: egg_fried_rice.md
    - Pho Soup: pho_soup.md
    - Goose Sous-vide: goose_sous_vide.md 
    - Tartare: tartare.md
theme:
    name: null
    custom_dir: 'theme/'

extra_css:
    - css/style.css